group=ray.labs
version=1.1.0
description=Multi-currency auction house plugin for Paper with multi-server support

org.gradle.jvmargs=-Xmx1200m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configuration-cache=false
