CREATE TABLE IF NOT EXISTS rayauction_auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id VARCHAR(36) NOT NULL,
    seller_name VARCHAR(16) NOT NULL,
    item_data BYTEA NOT NULL,
    item_material VARCHAR(64) NOT NULL,
    item_name VARCHAR(512) NOT NULL DEFAULT '',
    item_lore TEXT NOT NULL,
    item_category VARCHAR(16) NOT NULL DEFAULT 'other',
    item_amount INT NOT NULL DEFAULT 1,
    price NUMERIC(20, 4) NOT NULL,
    currency VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    buyer_id VARCHAR(36),
    version INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_auctions_status_expires ON rayauction_auctions (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_auctions_seller ON rayauction_auctions (seller_id, status);
CREATE INDEX IF NOT EXISTS idx_auctions_currency ON rayauction_auctions (currency, status);
CREATE INDEX IF NOT EXISTS idx_auctions_material ON rayauction_auctions (item_material);
CREATE INDEX IF NOT EXISTS idx_auctions_created ON rayauction_auctions (created_at);

CREATE TABLE IF NOT EXISTS rayauction_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL,
    buyer_id VARCHAR(36) NOT NULL,
    seller_id VARCHAR(36) NOT NULL,
    seller_name VARCHAR(16) NOT NULL,
    buyer_name VARCHAR(16) NOT NULL,
    item_data BYTEA NOT NULL,
    item_material VARCHAR(64) NOT NULL,
    item_amount INT NOT NULL DEFAULT 1,
    price NUMERIC(20, 4) NOT NULL,
    currency VARCHAR(32) NOT NULL,
    tax_amount NUMERIC(20, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_transaction_auction UNIQUE (auction_id)
);

CREATE INDEX IF NOT EXISTS idx_transactions_buyer ON rayauction_transactions (buyer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_seller ON rayauction_transactions (seller_id, created_at);

CREATE TABLE IF NOT EXISTS rayauction_limits (
    player_id VARCHAR(36) PRIMARY KEY,
    custom_limit INT,
    updated_at TIMESTAMP NOT NULL
);
