CREATE TABLE IF NOT EXISTS rayauction_ledger (
    player_id VARCHAR(36) NOT NULL,
    currency VARCHAR(32) NOT NULL,
    balance NUMERIC(20, 4) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_rayauction_ledger PRIMARY KEY (player_id, currency)
);

CREATE TABLE IF NOT EXISTS rayauction_mailbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(36) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    item_data BYTEA,
    item_material VARCHAR(64),
    item_amount INT NOT NULL DEFAULT 1,
    amount NUMERIC(20, 4),
    currency VARCHAR(32),
    auction_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    delivered BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_mailbox_pending ON rayauction_mailbox (player_id, delivered, id);

CREATE TABLE IF NOT EXISTS rayauction_sync_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    payload TEXT NOT NULL,
    server_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_sync_unprocessed ON rayauction_sync_events (processed, id);
CREATE INDEX IF NOT EXISTS idx_sync_created ON rayauction_sync_events (created_at);
